config/routes.rb
Rails.application.routes.draw do 
  root 'pages#home'

  #controller => action
  get 'register' => 'users#new'
  get 'users/edit'
  get 'users/show'
  get 'users/index'

  resources :users
  resources :articles

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/write'=>'articles#new'
  get 'articles/edit'
  get 'articles/show'
  get 'articles/index'
  get '/search'=> 'articles#search'
  get '/results'=> 'articles#results'	
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_one_attached :cover_photo
	belongs_to :user
	validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    has_one_attached :photo
    has_many :articles
    has_secure_password
    validates :password, presence: true
    validates :email, presence: true, length: { maximum:100 }
    
    def full_name
        self.first_name + " " + self.last_name
    end
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        Bcrypt::Password.create(string, cost:cost)
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update]
  
  def new
  	@article = Article.new
  end

  def create
    #POST /articles
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.author = current_user.full_name
  	if @article.save
  		p "article saved!"
  		redirect_to @article
  	else
  		p "Article rejected for errors"
  		p @article.errors.messages
  		render "new"
  end
end

  def edit

  end

  def update
    if @article.update(article_params)
      p "article succesfully updated"
      redirect_to @article
    else
      render "edit"
    end
  end

  def show
  	
  end

  def index
  	@articles = Article.all.order('CREATED_AT DESC')
  end

  def search

  end

  def results
    @results = params[:q]
    p params[:date_submitted]

    if params[:terms].to_i != 1
      p 'user did not agree'
      render 'search'
    end

    p params

    search_words = params[:q].downcase.split(' ')
    titles = Article.pluck(:title)
    matches= []
    @final_results = []
    search_words.each do |word|
      titles.each do |t|
        if t.downcase.include?(word)
          matches << t
        end
      end
    end
    p matches
    matches.each do |match|
        x = Article.where(title: match)
        x.each do |y|
          @final_results << y
        end
    end
    @final_results.uniq!
  end

  private

  def article_params
  	params.require(:article).permit(:title, :author, :content, :cover_photo)
  end

  def find_article
  	@article = Article.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #authentication => You are who you say you are
  #authorization => What privileges does this person have? 
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to root_path
    else
      msg = "Invalid Credentials"
      p msg
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    log_out if logged_in?
    p 'Logged out succesfully'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      msg = "Thanks for signing up, #{user.email}!"
      flash[:notice] = msg
     redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :bio, :photo, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

    def long_article?(a)
       if a.content.split('').count > 100
            msg = 'You may want to read this later'
       else
            msg = 'This is a quick read'
       end
       return msg
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        sessions.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for (@article) do |f| %>
    <%= f.text_field :title, placeholder: 'Enter a title' %><br>
    <%= f.text_field :author, placeholder: 'Who are you?' %><br>
    <%= f.text_area :content, placeholder: "what is this post about" %><br>
    <%= f.file_field :cover_photo %><br>
    <%= f.submit "publish Article" %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing<em><%=@article.title%></em></h1>

<% = render 'form' %>

app/views/articles/index.html.erb
<h1>Recent Articles</h1>
<% @articles.each do |a| %>
<h3><%= link_to "#{a.title}", a %><br>
    <p><%= long_article?(a) %></p>
    <small>written <%= time_ago_in_words(a.created_at) %> ago </small>
</h3>
<% end %>

app/views/articles/new.html.erb
<h1>Write a new post</h1>

<%= render 'form' %>

app/views/articles/results.html.erb
<h1> Articles matching "<%= @results %>" </h1>

<% @final_results.each do |res| %>

<%= link_to "#{res.title}", res %> <br>

<% end %>

app/views/articles/search.html.erb
<h1>Search Articles</h1>

<%= form_tag('/results', method: 'get') do %>
    <%= text_field_tag(:q) %> <br>
    <%= date_field_tag(:date_submitted) %> <br>
    <%= check_box_tag(:terms) %> I agree to the terms<br><b>
    <%= submit_tag("Search") %>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= long_article?(@article) %></p>
<%= image_tag(@article.cover_photo, class: "img-responsive")%>
<p><em> written by <% @article.author %></em></p><br>
<%= link_to "Edit", edit_article_path %>
<p><%= @article.content %></p>

app/views/layouts/_header.html.erb
<ul>
    <li><%= link_to 'Register', register_path if current_user.nil? %></li>
    <li><%= link_to 'All Articles', articles_path %></li>
    <li><%= link_to 'Write an Article', write_path %></li>
    <li><%= link_to 'Search', search_path %></li>
    <% if logged_in? %>
        <li><%= link_to "#{current_user.email}", "#" %></li>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    <% else %>
        <li><%= link_to 'Log in', login_path %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Blog</h1>
<p>This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text.</p>

<h3><%= link_to "Write a New Article", write_path %></h3>
<h3><%= link_to "Recent Articles", articles_path %></h3>

<% if logged_in? %>
    You are logged in
<% end %>

app/views/shared/_messages.html.erb
<% if flash[:notice] %>
    <div><%= flash[:notice] %></div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Register as a writer.</h1>

<%= form_for (@user) do |f| %>
    <%= f.text_field :first_name, placeholder: 'First name' %><br>
    <%= f.text_field :last_name, placeholder: 'Last name' %><br>
    <%= f.email_field :email,  placeholder: 'Email', required: true %><br>

    <%= f.password_field :password,  placeholder: 'Password', required: true  %><br>
    <%= f.password_field :password_confirmation,  placeholder: 'Confirm Password', required: true %><br>

    <%= f.label :photo, 'Upload a Photo'%><br>
    <%=  f.file_field :photo %><br>
    <%= f.text_area :bio,  placeholder: 'Write Bio' %><br>

    <%= f.submit 'register' %>
    <% end %>

app/views/users/show.html.erb
<h1><% @user.first_name %> <% @user.last_name %></h1>

<%= @user.photo.attachment.nil? ? 'No user photo.' : image_tag(@user.photo, size: '100x100') %>
<p> You can reach <%= @user.first_name %> at <%= @user.email %>!
<p><%= @user.bio %></p>

<% unless @user.articles.empty? %>
    <h4>Articles wrtitten by <%= @user.full_name %></h4>
    <% @user.articles.each do |a| %>
        <% link_to "#{a.title}", a %><br>
    <% end %>

    <% else %>

    <h4><%= @user.first_name %> hasn't written any articles yet. </h4>

<% end %>